# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["tables"]

pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Matt Cleaver
tagline:          'Medieval to Modern Philosophy Notes'
url:              http://mattcleaver.github.io/medieval
shorturl:         mattcleaver.github.io/medieval
baseurl:          /medieval

author:
  name:           'Matt Cleaver'
  url:            https://twitter.com/mattcleaver

paginate:         1

# Custom vars
version:          1.0.1

github:
  repo:           #github.com/joshualande/joshualande.github.io

# This is the list of pages to include in the header of the website.
pages_list:       
  About: '/about/'
  Archive: '/archive/'
  Feed: '/atom.xml'

# Allow URL Redirects: 
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from
